In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


#### Numpy Most Useful feature Is N Dimensional Array Object(a.k.a ndarray)

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
a[0]

1

In [7]:
a[1]

2

In [8]:
#Numpy array is similar to list 

#### We have python list ,,  what is so special about numpy array

#### 3 main benefits of  numpy array over a python list

####  1) Less Memory
####  2) Fast
####  3) Convinient

In [10]:
#  Lets Comapre Pyhon list and numpy nd array

In [12]:
import time 
import sys

In [13]:
l = range(1000)
print(sys.getsizeof(4)*len(l))

28000


In [14]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


#### Here we can see that  size of list is greater than nupy array

####  Now lets see how numpy array is fast and convinient as copared to python list

In [16]:
size = 1000

In [22]:
l1 = range(size)
l2 = range(size)

In [23]:
a1 = np.arange(size)
a2 = np.arange(size)

In [24]:
# Pytghon list

In [25]:
start = time.time()

In [27]:
result = [(x+y) for x,y in zip(l1,l2)]


In [28]:
print("python list took", (time.time()-start)*1000)

python list took 145592.01550483704


In [31]:
# numpy array
start = time.time()

In [32]:
result = a1+a2

In [33]:
print("python array took", (time.time()-start)*1000)

python array took 123009.48643684387


In [35]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [36]:
a1+a2

array([5, 7, 9])

In [37]:
a2-a1

array([3, 3, 3])

In [38]:
a1*a1

array([1, 4, 9])

In [39]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [40]:
a2/a1

array([4. , 2.5, 2. ])

## Numpy Tutorial- Basic Array Oprration

In [41]:
a = np.array([5,6,7])

In [42]:
a[0]

5

In [43]:
a[1]

6

In [44]:
b = np.array([[1,2],[3,4],[5,6]])

In [45]:
b.ndim

2

In [46]:
a.ndim

1

In [47]:
a.itemsize

4

In [48]:
b.itemsize

4

In [49]:
a.dtype

dtype('int32')

In [50]:
b.dtype

dtype('int32')

In [51]:
c = np.array([[1,2], [2,3], [3,4]], dtype=np.float64)

In [52]:
c.dtype

dtype('float64')

In [53]:
c.ndim

2

In [54]:
c.itemsize

8

In [55]:
c

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

In [56]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
a

array([5, 6, 7])

In [58]:
a.size

3

In [59]:
b.size

6

In [60]:
c.size

6

In [61]:
a.shape

(3,)

In [62]:
b.shape

(3, 2)

In [63]:
c.shape

(3, 2)

In [66]:
d = np.array([[1,2], [3,4], [5,6]], dtype=complex)

In [68]:
d.dtype

dtype('complex128')

In [69]:
d.size

6

In [70]:
d.shape

(3, 2)

In [71]:
d.itemsize

16

In [72]:
d.ndim

2

In [73]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])