In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


#### Numpy Most Useful feature Is N Dimensional Array Object(a.k.a ndarray)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
#Numpy array is similar to list 

#### We have python list ,,  what is so special about numpy array

#### 3 main benefits of  numpy array over a python list

####  1) Less Memory
####  2) Fast
####  3) Convinient

In [7]:
#  Lets Comapre Pyhon list and numpy nd array

In [8]:
import time 
import sys

In [9]:
l = range(1000)
print(sys.getsizeof(4)*len(l))

28000


In [10]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


#### Here we can see that  size of list is greater than nupy array

####  Now lets see how numpy array is fast and convinient as copared to python list

In [11]:
size = 1000

In [12]:
l1 = range(size)
l2 = range(size)

In [13]:
a1 = np.arange(size)
a2 = np.arange(size)

In [14]:
# Pytghon list

In [15]:
start = time.time()

In [16]:
result = [(x+y) for x,y in zip(l1,l2)]


In [17]:
print("python list took", (time.time()-start)*1000)

python list took 411.00525856018066


In [18]:
# numpy array
start = time.time()

In [19]:
result = a1+a2

In [20]:
print("python array took", (time.time()-start)*1000)

python array took 520.993709564209


In [21]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [22]:
a1+a2

array([5, 7, 9])

In [23]:
a2-a1

array([3, 3, 3])

In [24]:
a1*a1

array([1, 4, 9])

In [25]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [26]:
a2/a1

array([4. , 2.5, 2. ])

## Numpy Tutorial- Basic Array Oprration

In [27]:
a = np.array([5,6,7]) # 1d array

In [28]:
a[0]

5

In [29]:
a[1]

6

In [30]:
b = np.array([[1,2],[3,4],[5,6]]) #2d array

In [31]:
b.ndim   #print dimension of array

2

In [32]:
a.ndim

1

In [33]:
a.itemsize  #print bytesize of each elemnt 

4

In [34]:
b.itemsize

4

In [35]:
a.dtype   #print datatype of aaray

dtype('int32')

In [36]:
b.dtype

dtype('int32')

In [37]:
c = np.array([[1,2], [2,3], [3,4]], dtype=np.float64)

In [38]:
c.dtype

dtype('float64')

In [39]:
c.ndim

2

In [40]:
c.itemsize

8

In [41]:
c

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

In [42]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a

array([5, 6, 7])

In [44]:
a.size #print size of array

3

In [45]:
b.size

6

In [46]:
c.size

6

In [47]:
a.shape # print height and width of array

(3,)

In [48]:
b.shape

(3, 2)

In [49]:
c.shape

(3, 2)

In [50]:
d = np.array([[1,2], [3,4], [5,6]], dtype=complex)

In [51]:
d.dtype

dtype('complex128')

In [52]:
d.size

6

In [53]:
d.shape

(3, 2)

In [54]:
d.itemsize

16

In [55]:
d.ndim

2

In [56]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

### Shape = This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

### ndim = This array attribute returns the number of array dimensions.
### itemsize = This array attribute returns the length of each element of array in bytes.


##### Np.zeros = The numpy.zeros() function returns a new array of given shape and type, with zeros.

In [57]:
import numpy as np

In [58]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
l = range(5)

In [61]:
l[0]

0

In [62]:
l[1]

1

In [63]:
l

range(0, 5)

In [64]:
m = np.arange(1,5)

In [65]:
m

array([1, 2, 3, 4])

In [66]:
m = np.arange(1,5,2)

In [67]:
m

array([1, 3])

In [68]:
""" numpy.arange() is an inbuilt numpy function that returns
an ndarray object containing evenly spaced values within a defined interval. 
For instance, you want to create values from 1 to 10; you can use numpy.arange() function.

Syntax:

numpy.arange(start, stop,step) 
"""

' numpy.arange() is an inbuilt numpy function that returns\nan ndarray object containing evenly spaced values within a defined interval. \nFor instance, you want to create values from 1 to 10; you can use numpy.arange() function.\n\nSyntax:\n\nnumpy.arange(start, stop,step) \n'

In [69]:
np.linspace(1,5,10) # here linspace will generate 10 equals number between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [70]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [71]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [72]:
a = np.array([[1,2],[3,4],[5,6]])

In [73]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
a.reshape(2,3) # The numpy.reshape() function shapes an array without changing data of array.

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [76]:
a.ravel() # The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements
         #  and with the same type as it). A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [77]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
a.min()

1

In [79]:
a.max()

6

In [80]:
a.sum()

21

In [81]:
a.sum(axis=0)

array([ 9, 12])

In [82]:
a.sum(axis=1)

array([ 3,  7, 11])

In [83]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [84]:
np.std(a)

1.707825127659933

### Some Mathametical Operation

In [86]:
a =  np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [87]:
a

array([[1, 2],
       [3, 4]])

In [88]:
b

array([[5, 6],
       [7, 8]])

In [89]:
a+b

array([[ 6,  8],
       [10, 12]])

In [90]:
a-b

array([[-4, -4],
       [-4, -4]])

In [91]:
a*b

array([[ 5, 12],
       [21, 32]])

In [92]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [93]:
a.dot(b)

array([[19, 22],
       [43, 50]])

### Indexing and sclicing

In [94]:
n = [6,7,8]

In [96]:
n[0:2]

[6, 7]

In [97]:
n[-1]

8

In [98]:
a = np.array([6,7,8])

In [99]:
a[0:2]

array([6, 7])

In [100]:
a[-1]

8

In [101]:
 a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
a[1,2]

6

In [104]:
a[0:6]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
a[0:,2]

array([3, 6, 9])

### iteration through arrays

In [108]:
a = np.array([[6,7,8], [1,2,3], [9,3,2]])

In [109]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [110]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [112]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


### Sticking together two arrays

In [113]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [114]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [115]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [116]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [117]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [119]:
a = np.arange(30).reshape(2,15)

In [120]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [121]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [123]:
result = np.hsplit(a,3)

In [124]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [125]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [126]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [133]:
result = np.vsplit(a,2)

In [134]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [135]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

 ### Indexing with bollean arrays

In [136]:
a = np.arange(12).reshape(3,4)

In [137]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
b = a>4

In [140]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [142]:
a[b] = -1

In [143]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])